#!/usr/bin/env bash

MASON_HOME=$(dirname $0) # may be relative
MASON_HOME=$(readlink -f $MASON_HOME) # now it is absolute

cd $MASON_HOME

. install-utils $MASON_HOME $@

echo ''

function setup_emacs_early_init {
    EMACS_HOME="$(get_emacs_home)"
    ret=$?
    if [ $ret != 0 ]; then
        return $ret
    fi

    src=${MASON_HOME}/emacs/early-init.el
    dst=${EMACS_HOME}/early-init.el

    install_symlink "$src" "$dst"
}

setup_gitconfig
install_copies
install_symlinks
add_to_emacs setup-mason
setup_emacs_early_init
