#!/usr/bin/env bash

MASON_HOME=$(dirname $0) # may be relative
MASON_HOME=$(readlink -f $MASON_HOME) # now it is absolute

cd $MASON_HOME

. install-utils $MASON_HOME $@

echo ''

function setup_gitconfig {
    if ! $no_prompt && [ ! -f git/.gitconfig.local.copy.home ]; then
        user 'setup .gitconfig? y/N'
        read -e do_gitconfig
        case "$do_gitconfig" in
            y*|Y*)
                # continue
                ;;
            *)
                return
                ;;
        esac

        user ' - Enter git author name'
        read -e git_name
        user ' - Enter git author email'
        read -e git_email

        sed -e "s/TEMPLATE_NAME/$git_name/" -e "s/TEMPLATE_EMAIL/$git_email/" git/gitconfig.local.base > git/.gitconfig.local.copy.home || exit

        success 'gitconfig'
    fi
}

function setup_emacs_early_init {
    EMACS_HOME="$(get_emacs_home)"
    ret=$?
    if [ $ret != 0 ]; then
        return $ret
    fi

    src=${MASON_HOME}/emacs/early-init.el
    dst=${EMACS_HOME}/early-init.el

    install_symlink "$src" "$dst"
}

setup_gitconfig

install_copies
install_symlinks

add_to_emacs setup-mason
setup_emacs_early_init

add_to_rc .bashrc 'MASON_HOME'
add_to_rc .zshrc 'MASON_HOME'

add_to_config i3 'MASON_HOME'
add_to_config sway 'MASON_HOME'
